# -*- coding: utf-8 -*-
"""dunn_index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16IcXRcP3ke55vTQ52dO2Lxo41ldhYMlw
"""

from sklearn import datasets 
from sklearn.cluster import KMeans 
from sklearn.metrics import davies_bouldin_score 

import numpy as np
temp =0
# loading the dataset 
data_file = "iris_data_012.txt"
X=  np.loadtxt(data_file, delimiter=",", usecols=range(0,4), dtype=np.float64)
z=[]
# K-Means 
for i in range(2,50):
  kmeans = KMeans(n_clusters=i, random_state=1).fit(X) 

  # we store the cluster labels 
  labels = kmeans.labels_ 

 # print(davies_bouldin_score(X, labels)) 
  z.append(davies_bouldin_score(X, labels))
for i in range(1,47):
  if z[i]<z[i-1] and z[i]<z[i+1]:
    temp=i+2
    break
print(temp)