# -*- coding: utf-8 -*-
"""silhouette.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gDnSfreOsusI924aP4ZaDw6_K-AImb3J
"""

from sklearn.datasets import make_blobs 
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt 
import numpy as np
mini = 1000000
temp=0
z=[]
print("\nLoading Iris data into memory \n")
data_file = "iris_data_012.txt"
data_x = np.loadtxt(data_file, delimiter=",", usecols=range(0,4), dtype=np.float64)
data_y = np.loadtxt(data_file, delimiter=",", usecols=[4], dtype=np.int)
X, Y = make_blobs()
for i in range(2,50):
  cluster = KMeans(n_clusters = i) 
  cluster_labels = cluster.fit_predict(data_x)
  silhouette_avg = silhouette_score(data_x, cluster_labels)
  z.append(silhouette_avg)
for i in range(1,47):
  if z[i]<z[i-1] and z[i]<z[i+1]:
    temp=z[i]
    mini = i+2
    break
print(temp,mini)

